### ISSUE TITLE
Have you tried to integrate it with Azure Functions DI

### ISSUE THREAD

**Issue by DibranMulder** [aletc1/examples-odata-azure-functions#1]
He Alejandro, first of all nice work! Secondly, have you tried to integrate it with Azure Functions dependency injection system? Building a new ServiceProvider and applying that to a new HttpRequest feels like some overhead. Why not adding the dependencies to the existing ServiceProvider? Or do some dependencies conflict with existing ones for Azure Functions? Thanks in advance

**Comment by aletc1** [comment]
Hi @DibranMulder,

I havent tried... It is indeed an "ackward workaround" to not use the default DI system. I didnt feel comfortable adding MVC middlewares to the main DI system since wouldn be used by the functions, and that might add some overhead. That is why I prefer to memoize _provider  and _routeBuilder over having it added to the main DI system... feels more clean for me.

But if you manage to integrate it having better results, please share your experience. I am sure it will contribute to improve this workaround.
